version: "3"
services:
  snakov:
    ports:
      - "3000:3000"
    environment:
      OUTGOING_WEBHOOK_TOKEN: 123
      RESPONSE_CHANCE: 0.5
      RACK_ENV: development
      LOCAL_REDIS_URL: redis://redis:6379
      MAX_WORDS: 100
      API_TOKEN: abc123
      REPLY_REGEX: (sn|m)arkov
      MUTE_REGEX: (sn|m)arkov mute
      MEMCACHEDCLOUD_SERVERS: memcached:11211
    volumes:
      - .:/home/app
    build: .
    command:
      - passenger
      - start
    depends_on:
      - redis
      - memcached


  redis:
    image: redis:5-alpine
    ports:
      - "6379:6379"

  memcached:
    image: memcached:1.5.15
    ports:
      - "11211:11211"
